pipeline:
 build:
  image: node:8-alpine
  commands:
   - npm install
   - npm run build

 publish:
  image: plugins/docker
  username: ashmits
  password: gthtgenmt145
  repo: ashmits/dashboard_beta
 
 deploy:
  image: drillster/drone-rsync
  user: root
  hosts:
   - 207.154.237.9
  port: 22
  recursive: true
  source: ./public
  target: /home/skins4real/dashboard_beta
  secrets: [ plugin_key ]