version: "2"
services:
  #nginx:
  #  build:
  #    context: ./
  #    dockerfile: Dockerfile
  #  restart: always
  #  volumes:
  #    - .:/var/www
  #  environment:
  #    - NGINX_SERVER_NAME=localhost
  #    - NGINX_DOCROOT=public
  #  ports:
  #    - "7003:80"

  nodejs:
    build:
      context: ./
      dockerfile: DockerfileNode
    volumes:
      - .:/var/www
    command: npm install
    ports:
      - "3334:3333"

